version: '3'

services:
  jenkins:
    container_name: jenkins
    build: ./jenkins/
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - buddy_mlir:/opt/buddy_mlir
    restart: on-failure

  buddy:
    container_name: buddy
    build:
      context: ./compiler-containers/
      dockerfile: Dockerfile
    volumes:
      - buddy_mlir:/buddy-mlir
    deploy:
      restart_policy:
        condition: none
    entrypoint: ["/bin/sh", "-c", "echo 'buddy_mlir MOUNTED'"]
    restart: "no"
    depends_on:
      - jenkins

volumes:
  jenkins_home:
  buddy_mlir: